# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Magnus S. Remøe
email: mremoe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Founder, surfer, engineer, and a whole lot of other things.
tagline: Founder, surfer, engineer, and a whole lot of other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://magnusremoe.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: magnusremoe
github_username:  cestbalez
linkedin_username:  magnusremoe
logo: assets/images/logo.webp

# Navigation settings
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Footer settings
footer_links:
  - title: GitHub
    url: https://github.com/cestbalez
    icon: fab fa-github-square
  - title: Twitter
    url: https://twitter.com/magnusremoe
    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/magnusremoe/
    icon: fab fa-linkedin
copyright: "This site is made with <3 by me, *straight from the heart.*"

# Post settings
author:
  name: Magnus S. Remøe
  twitter: magnusremoe
  github: cestbalez
  linkedin: magnusremoe
  picture: /assets/images/avatar.jpg
read_time: true
words_per_minute: 200

# Style settings
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
# skin: "/assets/css/skins/dark.css"

# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
